config/routes.rb
Rails.application.routes.draw do
  resources :projects do resources :estimates, only: [:new, :create] end
  resources :teams
  resources :estimates

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root "projects#index"
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :project
  #belongs_to :user
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  # GET /estimates/new
  def new
    @project = Project.find(params[:project_id])
    @estimate = @project.estimates.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @project = Project.find(params[:project_id])
    @estimate = @project.estimates.create(params[:estimate].permit(:estimate, :case_best, :case_worst, :case_expected))

    #respond_to do |format|
        redirect_back(fallback_location: root_path)
    #  else
    #    render :new
      #end
    #end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    @project = Project.find(params[:project_id])

    respond_to do |format|
      if @estimate.update(estimate_params)
        redirect_to project_path(@project)
      else
        render :edit
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @estimate = @project.estimates.find(params[:id])

    @estimate.destroy
    respond_to do |format|
      redirect_to project_path(@project)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:estimate, :case_best, :case_worst, :case_expected)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= simple_form_for([@project, @estimate]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="columns">
    <div class="column">
      <p class="has-text-grey">Worst Case:</p>
      <%= f.input_field :case_worst, required: true, autofocus: true, class:'input is-danger has-background-dark has-text-grey' %>
    </div>
    <div class="column">
      <p class="has-text-grey">Expected Case:</p>
      <%= f.input_field :case_expected, required: true, autofocus: true, class:'input is-warning has-background-dark has-text-grey' %>
    </div>
    <div class="column">
      <p class="has-text-grey">Best Case:</p>
      <%= f.input_field :case_best, required: true, autofocus: true, class:'input is-success has-background-dark has-text-grey' %>
    </div>
  </div>

  <%= f.button :submit, class: 'button is-success has-box-shadow' %>


<% end %>

app/views/estimates/edit.html.erb
<h1>Editing Estimate</h1>

<%= render 'form', estimate: @estimate %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<p id="notice"><%= notice %></p>

<%= simple_form_for(Estimate.new) %>

<h1>Estimates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= link_to 'Show', estimate %></td>
        <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
        <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estimate', new_estimate_path %>

app/views/estimates/new.html.erb
<h1>New Estimate</h1>

<%= render 'form', estimate: @estimate %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %>